"""Phase 7: assemble REPORT.md + equity-curve chart from whatever results exist.

Reads src/rl_agent/logs/ (baselines_test.json, ppo_*/test_metrics.json and
equity curves) and degrades gracefully: sections for missing artifacts say so
instead of failing. Safe to run at any stage.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.common.config import load_config
from src.rl_agent.train_ppo import ABLATIONS, LOGS_DIR

METRIC_COLS = [("total_return_pct", "Total %"), ("cagr_pct", "CAGR %"),
               ("sharpe", "Sharpe"), ("sortino", "Sortino"),
               ("max_drawdown_pct", "MaxDD %"), ("turnover_x_equity", "Turnover x")]


def _row(name: str, m: dict) -> str:
    return "| " + " | ".join([name] + [str(m.get(k, "—")) for k, _ in METRIC_COLS]) + " |"


def main() -> None:
    cfg = load_config()
    lines = [
        "# Capstone3 — Out-of-Sample Results",
        "",
        f"Test window: **{cfg.rl.test_start} → {cfg.data.end_date}** | "
        f"seed {cfg.project.seed} | reward: {cfg.env.reward.type}",
        "",
        "| Strategy | " + " | ".join(h for _, h in METRIC_COLS) + " |",
        "|" + "---|" * (len(METRIC_COLS) + 1),
    ]

    curves, baseline_curves = {}, {}
    baselines_file = LOGS_DIR / "baselines_test.json"
    if baselines_file.exists():
        for name, r in json.loads(baselines_file.read_text()).items():
            lines.append(_row(name, r["metrics"]))
            baseline_curves[name] = r["equity_curve"]
    else:
        lines.append("| _baselines not run_ |" + " |" * len(METRIC_COLS))

    for arm in ABLATIONS:
        mfile = LOGS_DIR / f"ppo_{arm}" / "test_metrics.json"
        if mfile.exists():
            lines.append(_row(f"PPO {arm}", json.loads(mfile.read_text())))
            cfile = mfile.parent / "test_equity_curve.csv"
            if cfile.exists():
                curves[f"PPO {arm}"] = [float(x) for x in
                                        cfile.read_text().splitlines()[1:]]
        else:
            lines.append(_row(f"PPO {arm} — _not trained_", {}))

    if curves or baseline_curves:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(10, 5))
        for name, curve in curves.items():
            ax.plot(range(len(curve)), curve, label=name, linewidth=2)
        for name, curve in baseline_curves.items():
            ax.plot(range(len(curve)), curve, label=name, linestyle="--", alpha=0.7)
        ax.set_xlabel("test day")
        ax.set_ylabel("equity (INR)")
        ax.legend()
        fig.tight_layout()
        fig.savefig(ROOT / "equity_curves.png", dpi=150)
        lines += ["", "![equity curves](equity_curves.png)"]

    lines += ["", "_Generated by scripts/report.py — metrics from src/rl_agent/logs/._"]
    (ROOT / "REPORT.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote REPORT.md ({len(curves)} PPO curves plotted)")


if __name__ == "__main__":
    main()
